
import jsPDF from 'jspdf';
import { Transaction, BudgetMap } from '../types';
import { formatMoney } from '../utils';

export const generateMonthlyReport = (
    transactions: Transaction[], 
    budgets: BudgetMap, 
    currentDate: Date,
    currency: string
) => {
    const doc = new jsPDF();
    const monthName = currentDate.toLocaleString('default', { month: 'long', year: 'numeric' });
    
    doc.setFillColor(16, 185, 129);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("Financial Report", 14, 25);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(monthName, 14, 32);

    const monthlyTxs = transactions.filter(t => {
        const d = new Date(t.date);
        return d.getMonth() === currentDate.getMonth() && d.getFullYear() === currentDate.getFullYear();
    });
    
    const income = monthlyTxs.filter(t => t.type === 'income').reduce((a,b) => a + b.amount, 0);
    const expense = monthlyTxs.filter(t => t.type === 'expense').reduce((a,b) => a + b.amount, 0);
    const savings = income - expense;
    
    const budgetKey = currentDate.getFullYear() + '-' + String(currentDate.getMonth() + 1).padStart(2, '0');
    const budget = budgets[budgetKey] || budgets['default'] || 0;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Monthly Summary", 14, 55);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    
    let y = 65;
    doc.text(`Total Income: ${formatMoney(income, currency, false)}`, 14, y);
    doc.text(`Total Expense: ${formatMoney(expense, currency, false)}`, 110, y);
    y += 10;
    doc.text(`Net Savings: ${formatMoney(savings, currency, false)}`, 14, y);
    doc.text(`Budget Goal: ${formatMoney(budget, currency, false)}`, 110, y);
    
    y += 20;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Top Expense Categories", 14, y);
    y += 10;
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    const categories: Record<string, number> = {};
    monthlyTxs.filter(t => t.type === 'expense').forEach(t => {
        categories[t.category] = (categories[t.category] || 0) + t.amount;
    });
    const sortedCats = Object.entries(categories).sort((a,b) => b[1] - a[1]).slice(0, 5);
    
    sortedCats.forEach(([cat, amount]) => {
        doc.text(`${cat}: ${formatMoney(amount, currency, false)}`, 14, y);
        y += 7;
    });

    y += 15;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Recent Transactions", 14, y);
    y += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Date", 14, y);
    doc.text("Merchant", 50, y);
    doc.text("Category", 120, y);
    doc.text("Amount", 170, y);
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.line(14, y, 196, y);
    y += 6;

    doc.setTextColor(0, 0, 0);
    monthlyTxs.sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime()).slice(0, 15).forEach(tx => {
        const dateStr = new Date(tx.date).toLocaleDateString();
        doc.text(dateStr, 14, y);
        doc.text(tx.title.substring(0, 25), 50, y);
        doc.text(tx.category, 120, y);
        doc.text(formatMoney(tx.amount, currency, false), 170, y);
        y += 7;
    });

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Emerald Finance", 14, 285);

    doc.save(`Emerald_Report_${monthName}.pdf`);
};
